language: php

php:
- 5.6

sudo: false

branches:
  only:
  - source

before_install:
- openssl aes-256-cbc -K $encrypted_d3ec3c12d2f5_key -iv $encrypted_d3ec3c12d2f5_iv
  -in phpab.github.io.enc -out .travis/phpab.github.io -d
- travis_retry composer self-update
- travis_retry gem install sass

install:
- travis_retry curl -O https://download.sculpin.io/sculpin.phar
- travis_retry chmod +x sculpin.phar
- travis_retry php sculpin.phar install

script:
- php sculpin.phar generate --env=prod

after_script:
- bin/publish.sh

notifications:
  email: false
  irc: irc.freenode.org#phpab
